Switching to Expo
PlayerData/react-native-mcu-manager pull request #81
Opened 2023-11-06 11:21 UTC by Koalk

Facilitate the increments in native libraries and use prebuild for the example app to reduce the amount of managed code in this repo.

General refactor of the library to use expo and expo prebuild.
Closes https://github.com/PlayerData/react-native-mcu-manager/issues/70

---------------------

Self Review:

* [ ] Appropriate test coverage
* [ ] Relevant Documentation updated

Smoke Tests:

* [x] Tested with the example app
* [x] Tested as an integrated library on another app

2023-11-06 11:23 UTC, ball-hayden commented on README.md
> +- [Documentation for the latest stable release](https://docs.expo.dev/versions/latest/sdk/@playerdata/react-native-mcu-manager/)
We should remove these links.

The old `Usage` section is probably still useful.

2023-11-06 11:36 UTC, ball-hayden commented on example/App.tsx
> +import * as Location from 'expo-location';
Do we need location?

2023-11-06 11:36 UTC, ball-hayden commented on example/src/BLEService.ts
> +  disconnectDevice = () => {
We should refactor this to be an `async` function.

2023-11-06 11:36 UTC, ball-hayden commented on example/src/BLEService.ts
> +  disconnectDeviceById = (id: DeviceId) =>
This can also be `async`?

2023-11-06 11:36 UTC, ball-hayden commented on example/src/BLEService.ts
> +    new Promise<Device>((resolve, reject) => {
We can simplify this with `await` and avoid returning the promise.

Not entirely sure what the behaviour of an async function returning a promise is, but suspect it's a double promise.

2023-11-06 13:39 UTC, ball-hayden commented on example/ios/Podfile
> +require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
Shouldn't this be gitignored now?

2023-11-06 14:54 UTC, saty9 submitted a review, later dismissed

2023-11-06 15:05 UTC, ball-hayden requested changes
We've ended up with bits of the example app back in.

Also the commit message needs rewording - `BREAKING CHANGE` needs to be in the footer (i.e. following at least one newline) e.g.:

```
feat(expo): Switch to an Expo Module structure

BREAKING CHANGE: Requires that the using app is set up to use Expo Modules
```

2023-11-07 09:07 UTC, Koalk commented on example/ios/Podfile
> +require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
yep... eveything inside example/ios and example/android should be deleted and ignored now.

2023-11-07 09:08 UTC, Koalk commented
> We've ended up with bits of the example app back in.
> 
> Also the commit message needs rewording - `BREAKING CHANGE` needs to be in the footer (i.e. following at least one newline) e.g.:
> 
> ```
> feat(expo): Switch to an Expo Module structure
> 
> BREAKING CHANGE: Requires that the using app is set up to use Expo Modules
> ```

commit lint didn't let me make a commit message that was that big. I'll do it with the no verify flag if I can't get it in otherwise

2023-11-07 09:13 UTC, ball-hayden approved these changes

2023-11-07 09:24 UTC, merged